# Generated by Django 3.2.8 on 2021-10-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.CharField(max_length=5)),
                ('customer_id', models.CharField(max_length=5)),
                ('fuel', models.CharField(max_length=5)),
                ('vehicle_segment', models.CharField(max_length=3)),
                ('premium', models.CharField(max_length=6)),
                ('bodily_injury_liability', models.CharField(max_length=1)),
                ('personal_injury_protection', models.CharField(max_length=1)),
                ('property_damage_liability', models.CharField(max_length=1)),
                ('collision', models.CharField(max_length=1)),
                ('comprehensive', models.CharField(max_length=1)),
                ('customer_gender', models.CharField(max_length=11)),
                ('customer_income_group', models.CharField(max_length=20)),
                ('customer_region', models.CharField(max_length=5)),
                ('customer_marital_status', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
