# Generated by Django 3.2.8 on 2021-10-26 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='date_of_purchase',
            field=models.DateField(default="2018/01/05"),
            preserve_default=False,


            
        ),
        migrations.AddField(
            model_name='insurance',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='insurance_data.position'),
            preserve_default=False,
        ),
    ]
