# Generated by Django 3.2.8 on 2021-10-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_data', '0003_alter_insurance_date_of_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='bodily_injury_liability',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='collision',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='comprehensive',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='customer_marital_status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='personal_injury_protection',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='property_damage_liability',
            field=models.CharField(max_length=255),
        ),
    ]
